-- ── partner_health_scores ─────────────────────────────────────────────────────
-- One row per partner (upserted by recompute_partner_health_score).
-- Stores the latest computed overall score, category breakdown, and derived
-- risk/growth/confidence scores.

CREATE TABLE public.partner_health_scores (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  partner_id       uuid        NOT NULL UNIQUE REFERENCES public.partners(id) ON DELETE CASCADE,
  overall_score    smallint    CHECK (overall_score BETWEEN 0 AND 100),
  health_status    text        CHECK (health_status IN ('healthy','at_risk','critical','insufficient_data')),
  risk_score       smallint    CHECK (risk_score BETWEEN 0 AND 100),
  growth_score     smallint    CHECK (growth_score BETWEEN 0 AND 100),
  confidence_score smallint    CHECK (confidence_score BETWEEN 0 AND 100),
  category_scores  jsonb,
  score_debug      jsonb,
  model_version    text        NOT NULL DEFAULT 'phi-1',
  computed_at      timestamptz NOT NULL DEFAULT now(),
  created_at       timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.partner_health_scores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "partner_health_scores: select visible"
  ON public.partner_health_scores FOR SELECT
  USING (public.can_view_partner(auth.uid(), partner_id));

CREATE POLICY "partner_health_scores: insert visible"
  ON public.partner_health_scores FOR INSERT
  WITH CHECK (public.can_view_partner(auth.uid(), partner_id));

CREATE POLICY "partner_health_scores: update visible"
  ON public.partner_health_scores FOR UPDATE
  USING (public.can_view_partner(auth.uid(), partner_id));


-- ── partner_health_alerts ─────────────────────────────────────────────────────
-- Rule-based alerts generated by evaluate_partner_alerts().
-- Alerts are upserted (one active alert per type per partner).
-- Resolved when the trigger condition no longer holds.

CREATE TABLE public.partner_health_alerts (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  partner_id   uuid        NOT NULL REFERENCES public.partners(id) ON DELETE CASCADE,
  alert_type   text        NOT NULL,
  severity     text        NOT NULL CHECK (severity IN ('critical','warning','info')),
  message      text        NOT NULL,
  triggered_at timestamptz NOT NULL DEFAULT now(),
  resolved_at  timestamptz,
  is_active    boolean     NOT NULL DEFAULT true,
  created_at   timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.partner_health_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "partner_health_alerts: select visible"
  ON public.partner_health_alerts FOR SELECT
  USING (public.can_view_partner(auth.uid(), partner_id));

CREATE POLICY "partner_health_alerts: insert visible"
  ON public.partner_health_alerts FOR INSERT
  WITH CHECK (public.can_view_partner(auth.uid(), partner_id));

CREATE POLICY "partner_health_alerts: update visible"
  ON public.partner_health_alerts FOR UPDATE
  USING (public.can_view_partner(auth.uid(), partner_id));

CREATE POLICY "partner_health_alerts: delete admin only"
  ON public.partner_health_alerts FOR DELETE
  USING (public.is_admin(auth.uid()));
